In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler

In [2]:
# Now load in the dataset with Pandas
dataset = pd.read_csv('./Downloads/heart.csv')
# Print out part of the dataset to ensure proper loading
df = dataset.copy()
print(df.head(5))

   Person  2nd Heart Attack  Treatment of Anger  Trait Anxiety
0       1                 1                   1             70
1       2                 1                   1             80
2       3                 1                   1             50
3       4                 1                   0             60
4       5                 1                   0             40


In [3]:
#Lets Separate dependent and independent variable
x= df[['Treatment of Anger', 'Trait Anxiety']]
y = df[['2nd Heart Attack']]
x.head()

Treatment of Anger  Trait Anxiety
0                   1             70
1                   1             80
2                   1             50
3                   0             60
4                   0             40

In [4]:
y.head()

2nd Heart Attack
0                 1
1                 1
2                 1
3                 1
4                 1

In [5]:
# lets split the data into train and test 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=31)
# Create an instance of the scaler and apply it to the data
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [32]:
# Display the test data sets 
X_test

array([[ 1.19522861, -0.47623957],
       [ 1.19522861,  0.99577364],
       [-0.83666003,  0.62777034]])

In [33]:
# import the logisticregression algorithm to fit to the training data
from sklearn.linear_model import LogisticRegression
logistic_clf = LogisticRegression(random_state = 0)
logistic_clf.fit(X_train, y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [34]:
## Lets print out the Coefficient and intercept which we find from the logistic algorithm
print(logistic_clf.coef_)
print(logistic_clf.intercept_)

[[-0.39016116  0.93324057]]
[-0.15094771]


In [42]:
X_test

array([[ 1.19522861, -0.47623957],
       [ 1.19522861,  0.99577364],
       [-0.83666003,  0.62777034]])

In [44]:
# we do have two coefficent for two independent variable
𝑊1= -0.39016116 # Coefficent Treatment of Anger
𝑊2= 0.93324057 # Coefficent Trait Anxiety
𝑊0= -0.15094771 # intercept or bias

In [45]:
#(Equation) z:= 𝑊1*Person + 𝑊2*Treatment of Anger + W3*Trait Anxiety + 𝑊0
z1 =((1.19522861*𝑊1) +(-0.47623957*𝑊2) +𝑊0)
z1

-1.0617255787061426

In [46]:
# Apply an above equation to get the real value as value
z2 =((X_test[1][0]*𝑊1) + (X_test[1][1]*𝑊2)  +𝑊0)
z3 =((X_test[2][0]*𝑊1) + (X_test[2][1]*𝑊2)  +𝑊0)
z1,z2,z3

(-1.0617255787061426, 0.31201686578499566, 0.7613452829471787)

In [47]:
# we obtain the same real value using the decison function
logistic_clf.decision_function(X_test)

array([-1.06172557,  0.31201687,  0.76134529])

In [19]:
# Let's define our sigmoid function 
def sigmoid(z):
    return 1.0 / (1 + np.exp(-z))

In [20]:
# lets convert the real value between 0 and 1 using the sigmoid function
sigmoid(z1),sigmoid(z2),sigmoid(z3)

(0.05260242541065003, 0.926687192608052, 0.9110796576409018)

In [21]:
# Below we use predict_proba to obtain the same as above to convert between 0 and 1 
logistic_clf.predict_proba(X_test)[:,1]

array([0.05260243, 0.92668719, 0.91107966])

In [22]:
#  Since we obtain the probablity between 0 and 1 from the simoid function 
# we will use Decison boundary  or threshold to classify the class
y_pred = logistic_clf.predict(X_test)
y_pred

array([0, 1, 1])